plugins {
    id 'java'
    id 'org.springframework.boot' version '2.6.2'   // версия spring-boot
    id 'io.spring.dependency-management' version '1.1.4'    // автоматически устраняет несовместимость версий библиотек
    id 'io.freefair.lombok' version '8.6'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'   // версии не указываются т.к. подтянутся dependency-management плагином нужные версии, без конфликтов
    implementation 'org.postgresql:postgresql'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation "org.mockito:mockito-core:2.25.1"
}

test {
    useJUnitPlatform()
}
