spring:
  application:
  name: spring_boot

  profiles:
    active: qa

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate
        batch_size: 50  # для update, delete, insert запросов, чтоб одним запросом в БД уходили указанное кол-во записей
        fetch_size: 10  # для select запросов, чтоб из общего результата select-запроса в приложение подтягивались из БД куски указанного размера

  liquibase:
    change-log: classpath*:db.changelog/db.changelog-master.yaml

# настройка уровня для вывода логирования (WARN и выше)
logging:
  level:
    root: info
    # также можно настроить уровень логирования для конкретного пакета / класса
    org.example.database.pool.ConnectionPool: warn
    # запись логов в файл
#  file:
#    name: example.log
#    path: /

db:
  username: ${username.value:postgres}  # если не будет передан параметр 'username.value' (например через run->edit configs->VMOptions или program.arguments и т.д.), то подставится дефолтный - 'postgres'
  password: ${db.username}  # подставится значение из параметра выше
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost, 127.0.0.1

# Map<K,V>
  properties:
    first: 123
    second: 567
    third.value: Third

# объект
  pool:
    size: 12
    timeout: 10

# список объектов
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3
